spring.application.name=songless
spring.sql.init.mode=always
spring.datasource.url=${URL_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${SENHA_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.max-lifetime=1800